<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Additional MHW outputs in R and Python • heatwaveR</title>
<!-- jquery --><script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha384-nrOSfDHtoPMzJHjVTdCopGqIqeYETSXhZDFyniQ8ZHcVy08QesyHcnOUpMpqnmWq" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/spacelab/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script><!-- Font Awesome icons --><link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.7.1/clipboard.min.js" integrity="sha384-cV+rhyOuRHc9Ub/91rihWcGmMmCXDeksTtCihMupQHSsi8GIIRDG0ThDc3HGQFJ3" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../jquery.sticky-kit.min.js"></script><script src="../pkgdown.js"></script><!-- docsearch --><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css">
<link href="../docsearch.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script><meta property="og:title" content="Additional MHW outputs in R and Python">
<meta property="og:description" content="This vignette compares the code/work flow for altering the additional arguments found within the base Python and R function.">
<meta property="og:image" content="https://robwschlegel.github.io/heatwaveR/index.html/logo.png">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]--><!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=UA-118123016-1"></script><script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-118123016-1');
</script>
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">heatwaveR</a>
        <span class="label label-default" data-toggle="tooltip" data-placement="bottom" title="Released package">0.2.6.9000</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fa fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/OISST_preparation.html">OISST preparation</a>
    </li>
    <li>
      <a href="../articles/gridded_event_detection.html">Extreme event detection in gridded data</a>
    </li>
    <li>
      <a href="../articles/Climatologies_and_baselines.html">Alternative climatologies and baselines</a>
    </li>
    <li>
      <a href="../articles/Short_climatologies.html">Short climatologies</a>
    </li>
    <li>
      <a href="../articles/r_vs_python.html">Default MHW outputs in R and Python</a>
    </li>
    <li>
      <a href="../articles/r_vs_python_more.html">Additional MHW outputs in R and Python</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">News</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/robwschlegel/heatwaveR">
    <span class="fa fa-github fa-lg"></span>
     
    github
  </a>
</li>
      </ul>
<form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="search" class="form-control" name="search-input" id="search-input" placeholder="Search..." aria-label="Search for..." autocomplete="off">
</div>
      </form>
      
    </div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>Additional MHW outputs in R and Python</h1>
                        <h4 class="author">Robert W Schlegel</h4>
            
            <h4 class="date">2018-05-23</h4>
      
      
      <div class="hidden name"><code>r_vs_python_more.Rmd</code></div>

    </div>

    
    
<div id="overview" class="section level2">
<h2 class="hasAnchor">
<a href="#overview" class="anchor"></a>Overview</h2>
<p>Building on the identical default functionality shared between the two languages, this vignette goes further to look at the additional functionality contained within the two packages. Along the way the outputs are checked for consistency and all of the arguments for all of the functions are tweaked to look for irregularities. This is necessary before only one language is used to further investigate best practices for dealing with sub-optimal time series in the detection of MHWs.</p>
<p>Preferably this step could have been done programmatically, without creating an army of outputs as seen below. The R package <strong><code>reticulate</code></strong> does not seem to want to play along though so I must rather run the Python code, save the outputs, load them into R and compare the results natively in just R… So let’s get started.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tidyverse)
<span class="kw">library</span>(ggpubr)
<span class="kw">library</span>(heatwaveR)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(reticulate)
<span class="kw"><a href="http://www.rdocumentation.org/packages/reticulate/topics/use_python">use_condaenv</a></span>(<span class="st">"py27"</span>)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python"><span class="im">import</span> numpy <span class="im">as</span> np
<span class="im">from</span> datetime <span class="im">import</span> date
<span class="im">import</span> pandas <span class="im">as</span> pd
<span class="im">import</span> marineHeatWaves <span class="im">as</span> mhw
<span class="co"># The date values</span>
t <span class="op">=</span> np.arange(date(<span class="dv">1982</span>,<span class="dv">1</span>,<span class="dv">1</span>).toordinal(),date(<span class="dv">2014</span>,<span class="dv">12</span>,<span class="dv">31</span>).toordinal()<span class="op">+</span><span class="dv">1</span>)
<span class="co"># The temperature values</span>
sst <span class="op">=</span> np.loadtxt(<span class="bu">open</span>(<span class="st">"sst_WA.csv"</span>, <span class="st">"r"</span>), delimiter <span class="op">=</span> <span class="st">','</span>, skiprows <span class="op">=</span> <span class="dv">1</span>)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># The default python output from the previous comparison vignette</span>
default_py_event &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">"mhws_py.csv"</span>)
default_py_clim &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">"clim_py.csv"</span>)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># The default R output</span>
default_r &lt;-<span class="st"> </span><span class="kw"><a href="../reference/detect_event.html">detect_event</a></span>(<span class="kw"><a href="../reference/ts2clm.html">ts2clm</a></span>(<span class="dt">data =</span> sst_WA,
                                 <span class="dt">climatologyPeriod =</span> <span class="kw">c</span>(<span class="st">"1982-01-01"</span>, <span class="st">"2014-12-31"</span>)))</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">compare_event &lt;-<span class="st"> </span><span class="cf">function</span>(res_event_R, res_event_Python){
  <span class="co"># Remove non-numeric columns</span>
  res_event_num &lt;-<span class="st"> </span>res_event_R <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">    </span><span class="kw">select_if</span>(is.numeric)
  <span class="co"># Run the loop</span>
  res_event_cor &lt;-<span class="st"> </span><span class="kw">data.frame</span>()
  <span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(<span class="kw">colnames</span>(res_event_num))){
    <span class="cf">if</span>(<span class="kw">colnames</span>(res_event_num)[i] <span class="op">%in%</span><span class="st"> </span><span class="kw">colnames</span>(res_event_Python)){
      x1 &lt;-<span class="st"> </span>res_event_R[<span class="kw">colnames</span>(res_event_R) <span class="op">==</span><span class="st"> </span><span class="kw">colnames</span>(res_event_num)[i]]
      x2 &lt;-<span class="st"> </span>res_event_Python[<span class="kw">colnames</span>(res_event_Python) <span class="op">==</span><span class="st"> </span><span class="kw">colnames</span>(res_event_num)[i]]
      x &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">r =</span> <span class="kw">cor</span>(x1, x2), <span class="dt">var =</span> <span class="kw">colnames</span>(res_event_num)[i])
      <span class="kw">colnames</span>(x)[<span class="dv">1</span>] &lt;-<span class="st"> "r"</span>
      <span class="kw">rownames</span>(x) &lt;-<span class="st"> </span><span class="ot">NULL</span>
      } <span class="cf">else</span> {
        x &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">r =</span> <span class="ot">NA</span>, <span class="dt">var =</span> <span class="kw">colnames</span>(res_event_num)[i])
        <span class="co"># colnames(x) &lt;- colnames(res_event_R)[i]</span>
        }
    res_event_cor &lt;-<span class="st"> </span><span class="kw">rbind</span>(res_event_cor, x)
    }
  <span class="kw">return</span>(res_event_cor)
  }</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Compare default clims and intensities</span>
<span class="kw">cor</span>(default_r<span class="op">$</span>climatology<span class="op">$</span>seas, default_py_clim<span class="op">$</span>seas)</code></pre></div>
<pre><code>## [1] 0.9999999</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(default_r<span class="op">$</span>climatology<span class="op">$</span>seas) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(default_py_clim<span class="op">$</span>seas)</code></pre></div>
<pre><code>## [1] -1.98122</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor</span>(default_r<span class="op">$</span>climatology<span class="op">$</span>thresh, default_py_clim<span class="op">$</span>thresh)</code></pre></div>
<pre><code>## [1] 0.9999996</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(default_r<span class="op">$</span>climatology<span class="op">$</span>thresh) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(default_py_clim<span class="op">$</span>thresh)</code></pre></div>
<pre><code>## [1] -6.563516</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(default_r<span class="op">$</span>event<span class="op">$</span>intensity_cumulative) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(default_py_event<span class="op">$</span>intensity_cumulative)</code></pre></div>
<pre><code>## [1] 0.157388</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(default_r<span class="op">$</span>event<span class="op">$</span>intensity_max) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(default_py_event<span class="op">$</span>intensity_max)</code></pre></div>
<pre><code>## [1] 0.008520925</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Compare default events</span>
default_event &lt;-<span class="st"> </span><span class="kw">compare_event</span>(default_r<span class="op">$</span>event, default_py_event)
default_event</code></pre></div>
<pre><code>##            r                            var
## 1         NA                       event_no
## 2  1.0000000                    index_start
## 3  1.0000000                     index_peak
## 4  1.0000000                      index_end
## 5  1.0000000                       duration
## 6  0.9999991                 intensity_mean
## 7  0.9999997                  intensity_max
## 8  0.9996080                  intensity_var
## 9  1.0000000           intensity_cumulative
## 10 0.9999971       intensity_mean_relThresh
## 11 0.9999994        intensity_max_relThresh
## 12 0.9995685        intensity_var_relThresh
## 13 0.9999996 intensity_cumulative_relThresh
## 14 1.0000000             intensity_mean_abs
## 15 0.9990733              intensity_max_abs
## 16 0.9997267              intensity_var_abs
## 17 1.0000000       intensity_cumulative_abs
## 18 1.0000000                     rate_onset
## 19 1.0000000                   rate_decline</code></pre>
</div>
<div id="pctile-comparisons" class="section level2">
<h2 class="hasAnchor">
<a href="#pctile-comparisons" class="anchor"></a><code>pctile</code> comparisons</h2>
<p>Here we look at a few possible settings for the <code>pctile</code> argument and ensure that everything matches up.</p>
<p>First run and save the Python output.</p>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python"><span class="co"># pctile = 80</span>
mhws, clim <span class="op">=</span> mhw.detect(t, sst, pctile <span class="op">=</span> <span class="dv">80</span>)
mhws_df <span class="op">=</span> pd.DataFrame.from_dict(mhws)
mhws_df.to_csv(<span class="st">'mhws_py_pctile_80.csv'</span>, sep <span class="op">=</span> <span class="st">','</span>, index <span class="op">=</span> <span class="va">False</span>)
clim_df <span class="op">=</span> pd.DataFrame.from_dict(clim)
clim_df.to_csv(<span class="st">'clim_py_pctile_80.csv'</span>, sep <span class="op">=</span> <span class="st">','</span>, index <span class="op">=</span> <span class="va">False</span>)
<span class="co"># pctile = 95</span>
mhws, clim <span class="op">=</span> mhw.detect(t, sst, pctile <span class="op">=</span> <span class="dv">95</span>)
mhws_df <span class="op">=</span> pd.DataFrame.from_dict(mhws)
mhws_df.to_csv(<span class="st">'mhws_py_pctile_95.csv'</span>, sep <span class="op">=</span> <span class="st">','</span>, index <span class="op">=</span> <span class="va">False</span>)
clim_df <span class="op">=</span> pd.DataFrame.from_dict(clim)
clim_df.to_csv(<span class="st">'clim_py_pctile_95.csv'</span>, sep <span class="op">=</span> <span class="st">','</span>, index <span class="op">=</span> <span class="va">False</span>)
<span class="co"># pctile = 99</span>
mhws, clim <span class="op">=</span> mhw.detect(t, sst, pctile <span class="op">=</span> <span class="dv">99</span>)
mhws_df <span class="op">=</span> pd.DataFrame.from_dict(mhws)
mhws_df.to_csv(<span class="st">'mhws_py_pctile_99.csv'</span>, sep <span class="op">=</span> <span class="st">','</span>, index <span class="op">=</span> <span class="va">False</span>)
clim_df <span class="op">=</span> pd.DataFrame.from_dict(clim)
clim_df.to_csv(<span class="st">'clim_py_pctile_99.csv'</span>, sep <span class="op">=</span> <span class="st">','</span>, index <span class="op">=</span> <span class="va">False</span>)</code></pre></div>
<p>Then run the R output.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pctile_80_r &lt;-<span class="st"> </span><span class="kw"><a href="../reference/detect_event.html">detect_event</a></span>(<span class="kw"><a href="../reference/ts2clm.html">ts2clm</a></span>(<span class="dt">data =</span> sst_WA, <span class="dt">pctile =</span> <span class="dv">80</span>,
                                   <span class="dt">climatologyPeriod =</span> <span class="kw">c</span>(<span class="st">"1982-01-01"</span>, <span class="st">"2014-12-31"</span>)))
pctile_95_r &lt;-<span class="st"> </span><span class="kw"><a href="../reference/detect_event.html">detect_event</a></span>(<span class="kw"><a href="../reference/ts2clm.html">ts2clm</a></span>(<span class="dt">data =</span> sst_WA, <span class="dt">pctile =</span> <span class="dv">95</span>,
                                   <span class="dt">climatologyPeriod =</span> <span class="kw">c</span>(<span class="st">"1982-01-01"</span>, <span class="st">"2014-12-31"</span>)))
pctile_99_r &lt;-<span class="st"> </span><span class="kw"><a href="../reference/detect_event.html">detect_event</a></span>(<span class="kw"><a href="../reference/ts2clm.html">ts2clm</a></span>(<span class="dt">data =</span> sst_WA, <span class="dt">pctile =</span> <span class="dv">99</span>,
                                   <span class="dt">climatologyPeriod =</span> <span class="kw">c</span>(<span class="st">"1982-01-01"</span>, <span class="st">"2014-12-31"</span>)))</code></pre></div>
<p>Lastly load the Python output and compare the two.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Load Python</span>
pctile_80_py_event &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">"mhws_py_pctile_80.csv"</span>)
pctile_80_py_clim &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">"clim_py_pctile_80.csv"</span>)
pctile_95_py_event &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">"mhws_py_pctile_95.csv"</span>)
pctile_95_py_clim &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">"clim_py_pctile_95.csv"</span>)
pctile_99_py_event &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">"mhws_py_pctile_99.csv"</span>)
pctile_99_py_clim &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">"clim_py_pctile_99.csv"</span>)

<span class="co"># Compare clims and intensities</span>
<span class="co"># 80</span>
<span class="kw">cor</span>(pctile_80_r<span class="op">$</span>climatology<span class="op">$</span>seas, pctile_80_py_clim<span class="op">$</span>seas)</code></pre></div>
<pre><code>## [1] 0.9999999</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(pctile_80_r<span class="op">$</span>climatology<span class="op">$</span>seas) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(pctile_80_py_clim<span class="op">$</span>seas)</code></pre></div>
<pre><code>## [1] -1.98122</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor</span>(pctile_80_r<span class="op">$</span>climatology<span class="op">$</span>thresh, pctile_80_py_clim<span class="op">$</span>thresh)</code></pre></div>
<pre><code>## [1] 0.9999982</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(pctile_80_r<span class="op">$</span>climatology<span class="op">$</span>thresh) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(pctile_80_py_clim<span class="op">$</span>thresh)</code></pre></div>
<pre><code>## [1] -13.86432</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(pctile_80_r<span class="op">$</span>event<span class="op">$</span>intensity_cumulative) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(pctile_80_py_event<span class="op">$</span>intensity_cumulative)</code></pre></div>
<pre><code>## [1] 2.430907</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(pctile_80_r<span class="op">$</span>event<span class="op">$</span>intensity_max) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(pctile_80_py_event<span class="op">$</span>intensity_max)</code></pre></div>
<pre><code>## [1] -1.103187</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># 95</span>
<span class="kw">cor</span>(pctile_95_r<span class="op">$</span>climatology<span class="op">$</span>seas, pctile_95_py_clim<span class="op">$</span>seas)</code></pre></div>
<pre><code>## [1] 0.9999999</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(pctile_95_r<span class="op">$</span>climatology<span class="op">$</span>seas) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(pctile_95_py_clim<span class="op">$</span>seas)</code></pre></div>
<pre><code>## [1] -1.98122</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor</span>(pctile_95_r<span class="op">$</span>climatology<span class="op">$</span>thresh, pctile_95_py_clim<span class="op">$</span>thresh)</code></pre></div>
<pre><code>## [1] 0.9999999</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(pctile_95_r<span class="op">$</span>climatology<span class="op">$</span>thresh) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(pctile_95_py_clim<span class="op">$</span>thresh)</code></pre></div>
<pre><code>## [1] -3.382435</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(pctile_95_r<span class="op">$</span>event<span class="op">$</span>intensity_cumulative) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(pctile_95_py_event<span class="op">$</span>intensity_cumulative)</code></pre></div>
<pre><code>## [1] 0.05814455</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(pctile_95_r<span class="op">$</span>event<span class="op">$</span>intensity_max) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(pctile_95_py_event<span class="op">$</span>intensity_max)</code></pre></div>
<pre><code>## [1] 0.007503145</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># 99</span>
<span class="kw">cor</span>(pctile_99_r<span class="op">$</span>climatology<span class="op">$</span>seas, pctile_99_py_clim<span class="op">$</span>seas)</code></pre></div>
<pre><code>## [1] 0.9999999</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(pctile_99_r<span class="op">$</span>climatology<span class="op">$</span>seas) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(pctile_99_py_clim<span class="op">$</span>seas)</code></pre></div>
<pre><code>## [1] -1.98122</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor</span>(pctile_99_r<span class="op">$</span>climatology<span class="op">$</span>thresh, pctile_99_py_clim<span class="op">$</span>thresh)</code></pre></div>
<pre><code>## [1] 0.9999944</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(pctile_99_r<span class="op">$</span>climatology<span class="op">$</span>thresh) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(pctile_99_py_clim<span class="op">$</span>thresh)</code></pre></div>
<pre><code>## [1] 28.37769</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(pctile_99_r<span class="op">$</span>event<span class="op">$</span>intensity_cumulative) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(pctile_99_py_event<span class="op">$</span>intensity_cumulative)</code></pre></div>
<pre><code>## [1] -0.004070026</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(pctile_99_r<span class="op">$</span>event<span class="op">$</span>intensity_max) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(pctile_99_py_event<span class="op">$</span>intensity_max)</code></pre></div>
<pre><code>## [1] -0.0004070026</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Compare events</span>
<span class="co"># pctile_80_event &lt;- compare_event(pctile_80_r$event, pctile_80_py_event)</span>
pctile_95_event &lt;-<span class="st"> </span><span class="kw">compare_event</span>(pctile_95_r<span class="op">$</span>event, pctile_95_py_event)
pctile_95_event</code></pre></div>
<pre><code>##            r                            var
## 1         NA                       event_no
## 2  1.0000000                    index_start
## 3  1.0000000                     index_peak
## 4  1.0000000                      index_end
## 5  1.0000000                       duration
## 6  0.9999988                 intensity_mean
## 7  0.9999996                  intensity_max
## 8  0.9988690                  intensity_var
## 9  1.0000000           intensity_cumulative
## 10 0.9999979       intensity_mean_relThresh
## 11 0.9999468        intensity_max_relThresh
## 12 0.9988428        intensity_var_relThresh
## 13 0.9999999 intensity_cumulative_relThresh
## 14 1.0000000             intensity_mean_abs
## 15 0.9997819              intensity_max_abs
## 16 0.9990655              intensity_var_abs
## 17 1.0000000       intensity_cumulative_abs
## 18 0.9999998                     rate_onset
## 19 1.0000000                   rate_decline</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pctile_99_event &lt;-<span class="st"> </span><span class="kw">compare_event</span>(pctile_99_r<span class="op">$</span>event, pctile_99_py_event)
pctile_99_event</code></pre></div>
<pre><code>##            r                            var
## 1         NA                       event_no
## 2  1.0000000                    index_start
## 3  1.0000000                     index_peak
## 4  1.0000000                      index_end
## 5  1.0000000                       duration
## 6  1.0000000                 intensity_mean
## 7  1.0000000                  intensity_max
## 8  0.9995133                  intensity_var
## 9  1.0000000           intensity_cumulative
## 10 0.9999046       intensity_mean_relThresh
## 11 0.9999951        intensity_max_relThresh
## 12 0.9993605        intensity_var_relThresh
## 13 0.9999383 intensity_cumulative_relThresh
## 14 1.0000000             intensity_mean_abs
## 15 1.0000000              intensity_max_abs
## 16 0.9991256              intensity_var_abs
## 17 1.0000000       intensity_cumulative_abs
## 18 1.0000000                     rate_onset
## 19 1.0000000                   rate_decline</code></pre>
<p>There appears to be an issue with the results when the threshold is set to <code>pctile = 80</code> as Python detects one more event than R. Let’s take a closer look.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pctile_80_r_event &lt;-<span class="st"> </span>pctile_80_r<span class="op">$</span>event
pctile_80_py_event<span class="op">$</span>date_start[<span class="op">!</span>pctile_80_py_event<span class="op">$</span>date_start <span class="op">%in%</span><span class="st"> </span>pctile_80_r_event<span class="op">$</span>date_start]</code></pre></div>
<pre><code>## [1] "2013-12-30"</code></pre>
<p>The issue appears to be that the R code is joining across a four day gap, which it shouldn’t do. So I assume that the threshold is different between the languages. This is curious as the seasonal and threshold climatologies correlate nearly perfectly. Diving deeper, let’s pull out the clim values around the time of this event and see what we see.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pctile_80_r_clim &lt;-<span class="st"> </span>pctile_80_r<span class="op">$</span>climatology
pctile_80_r_clim_sub &lt;-<span class="st"> </span>pctile_80_r_clim[<span class="dv">11670</span><span class="op">:</span><span class="dv">11720</span>, ]
pctile_80_py_clim_sub &lt;-<span class="st"> </span>pctile_80_py_clim[<span class="dv">11670</span><span class="op">:</span><span class="dv">11720</span>, ]

r_fig &lt;-<span class="st"> </span><span class="kw">ggplot</span>(pctile_80_r_clim_sub, <span class="kw">aes</span>(<span class="dt">x =</span> t, <span class="dt">y =</span> temp)) <span class="op">+</span>
<span class="st">  </span><span class="kw"><a href="../reference/geom_flame.html">geom_flame</a></span>(<span class="kw">aes</span>(<span class="dt">y2 =</span> thresh)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">y =</span> thresh), <span class="dt">colour =</span> <span class="st">"Red"</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">y =</span> seas), <span class="dt">colour =</span> <span class="st">"grey20"</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">ggtitle</span>(<span class="st">"R code"</span>)

py_fig &lt;-<span class="st"> </span><span class="kw">ggplot</span>(pctile_80_py_clim_sub, 
                 <span class="kw">aes</span>(<span class="dt">x =</span> pctile_80_r_clim_sub<span class="op">$</span>t, <span class="dt">y =</span> pctile_80_r_clim_sub<span class="op">$</span>temp)) <span class="op">+</span>
<span class="st">  </span><span class="kw"><a href="../reference/geom_flame.html">geom_flame</a></span>(<span class="kw">aes</span>(<span class="dt">y2 =</span> thresh)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">y =</span> thresh), <span class="dt">colour =</span> <span class="st">"Red"</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">y =</span> seas), <span class="dt">colour =</span> <span class="st">"grey20"</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">ggtitle</span>(<span class="st">"Python code"</span>)

<span class="kw"><a href="http://www.rdocumentation.org/packages/ggpubr/topics/ggarrange">ggarrange</a></span>(r_fig, py_fig, <span class="dt">ncol =</span> <span class="dv">1</span>, <span class="dt">nrow =</span> <span class="dv">2</span>)</code></pre></div>
<p><img src="r_vs_python_more_files/figure-html/unnamed-chunk-6-1.png" width="384" style="display: block; margin: auto;"></p>
<p>As we may see in the figure above, the difference is not perceptible to the human eye. Looking very closely at the clim outputs manually one may see that in the R code, the threshold on <code>2013-12-29</code> is just below the temperature value due to a rounding difference from the Python code at the third decimal place.</p>
<p>Also above one may see that even though the values correlate nearly perfectly, the sum of the seasonal climatology value output by R are <code>1.98122</code> less than the Python output. Considering that there are 12053 values, the average difference is only <code>0.00016</code>, which is not terribly much at all. The issue appears to be in the calculation of the threshold climatology. This value is not consistently different based on the <code>pctile</code> value used. It varies quite a bit. With the sum difference at <code>pctile = 80</code> being <code>-13.86432</code>, the default of <code>pctile = 90</code> being <code>-6.563516</code>, <code>pctile = 95</code> being <code>-3.382435</code>, and <code>pctile = 80</code> being <code>28.37769</code>. This is strong evidence that the threshold values are being calculated using some different method that needs to be addressed. That being said, even at the largest difference of <code>28.37769</code>, that is still only an average difference per row of <code>0.002354409</code></p>
<p>Digging deeper still, let’s pull up the old <code>RmarineHeatWaves</code> code and run another comparison with that to see if this difference is due to newer changes in the development of the <code>heatwaveR</code> package.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ts &lt;-<span class="st"> </span>RmarineHeatWaves<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/RmarineHeatWaves/topics/make_whole">make_whole</a></span>(sst_WA)
default_r_old &lt;-<span class="st"> </span>RmarineHeatWaves<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/RmarineHeatWaves/topics/detect">detect</a></span>(<span class="dt">data =</span> ts, <span class="dt">climatology_start =</span> <span class="dv">1982</span>, <span class="dt">climatology_end =</span> <span class="dv">2014</span>)
default_r_old_event &lt;-<span class="st"> </span>default_r_old<span class="op">$</span>event
default_r_old_clim &lt;-<span class="st"> </span>default_r_old<span class="op">$</span>clim

<span class="co"># Compare default new and old R clims  and intensities</span>
<span class="kw">cor</span>(default_r<span class="op">$</span>climatology<span class="op">$</span>seas, default_r_old_clim<span class="op">$</span>seas_clim_year)</code></pre></div>
<pre><code>## [1] 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(default_r<span class="op">$</span>climatology<span class="op">$</span>seas) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(default_r_old_clim<span class="op">$</span>seas_clim_year)</code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor</span>(default_r<span class="op">$</span>climatology<span class="op">$</span>thresh, default_r_old_clim<span class="op">$</span>thresh_clim_year)</code></pre></div>
<pre><code>## [1] 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(default_r<span class="op">$</span>climatology<span class="op">$</span>thresh) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(default_r_old_clim<span class="op">$</span>thresh_clim_year)</code></pre></div>
<pre><code>## [1] 5.820766e-11</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(default_r<span class="op">$</span>event<span class="op">$</span>intensity_cumulative) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(default_py_event<span class="op">$</span>intensity_cumulative)</code></pre></div>
<pre><code>## [1] 0.157388</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(default_r<span class="op">$</span>event<span class="op">$</span>intensity_max) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(default_py_event<span class="op">$</span>intensity_max)</code></pre></div>
<pre><code>## [1] 0.008520925</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Compare default new and old R clims</span>
default_event &lt;-<span class="st"> </span><span class="kw">compare_event</span>(default_r<span class="op">$</span>event, default_r_old_event)
default_event</code></pre></div>
<pre><code>##     r                            var
## 1   1                       event_no
## 2   1                    index_start
## 3  NA                     index_peak
## 4  NA                      index_end
## 5   1                       duration
## 6  NA                 intensity_mean
## 7  NA                  intensity_max
## 8  NA                  intensity_var
## 9  NA           intensity_cumulative
## 10 NA       intensity_mean_relThresh
## 11 NA        intensity_max_relThresh
## 12 NA        intensity_var_relThresh
## 13 NA intensity_cumulative_relThresh
## 14 NA             intensity_mean_abs
## 15 NA              intensity_max_abs
## 16 NA              intensity_var_abs
## 17 NA       intensity_cumulative_abs
## 18  1                     rate_onset
## 19  1                   rate_decline</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Compare Python and old R clims  and intensities</span>
<span class="kw">cor</span>(default_py_clim<span class="op">$</span>seas, default_r_old_clim<span class="op">$</span>seas_clim_year)</code></pre></div>
<pre><code>## [1] 0.9999999</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(default_py_clim<span class="op">$</span>seas) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(default_r_old_clim<span class="op">$</span>seas_clim_year)</code></pre></div>
<pre><code>## [1] 1.98122</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor</span>(default_py_clim<span class="op">$</span>thresh, default_r_old_clim<span class="op">$</span>thresh_clim_year)</code></pre></div>
<pre><code>## [1] 0.9999996</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(default_py_clim<span class="op">$</span>thresh) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(default_r_old_clim<span class="op">$</span>thresh_clim_year)</code></pre></div>
<pre><code>## [1] 6.563516</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(default_py_event<span class="op">$</span>intensity_cumulative) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(default_r_old_event<span class="op">$</span>int_cum)</code></pre></div>
<pre><code>## [1] -0.157388</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(default_py_event<span class="op">$</span>intensity_max) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(default_r_old_event<span class="op">$</span>int_max)</code></pre></div>
<pre><code>## [1] -0.008520925</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Compare Python and old R clims</span>
default_event &lt;-<span class="st"> </span><span class="kw">compare_event</span>(default_r_old_event, default_py_event)
default_event</code></pre></div>
<pre><code>##     r                 var
## 1   1         index_start
## 2  NA          index_stop
## 3  NA            event_no
## 4   1            duration
## 5  NA            int_mean
## 6  NA             int_max
## 7  NA             int_var
## 8  NA             int_cum
## 9  NA int_mean_rel_thresh
## 10 NA  int_max_rel_thresh
## 11 NA  int_var_rel_thresh
## 12 NA  int_cum_rel_thresh
## 13 NA        int_mean_abs
## 14 NA         int_max_abs
## 15 NA         int_var_abs
## 16 NA         int_cum_abs
## 17 NA       int_mean_norm
## 18 NA        int_max_norm
## 19  1          rate_onset
## 20  1        rate_decline</code></pre>
</div>
<div id="smoothpercentilewidth-comparisons" class="section level2">
<h2 class="hasAnchor">
<a href="#smoothpercentilewidth-comparisons" class="anchor"></a><code>smoothPercentileWidth</code> comparisons</h2>
<p>Seeing now that the choice of the <code>pctile</code> threshold may create results different enough as to produce a different counts of events, we need to look closer at the different arguments. I have my suspicions that the smoothing of the threshold values may be the culprit here.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">spw_no_r &lt;-<span class="st"> </span><span class="kw"><a href="../reference/detect_event.html">detect_event</a></span>(<span class="kw"><a href="../reference/ts2clm.html">ts2clm</a></span>(<span class="dt">data =</span> sst_WA, <span class="dt">smoothPercentile =</span> <span class="ot">FALSE</span>,
                                <span class="dt">climatologyPeriod =</span> <span class="kw">c</span>(<span class="st">"1982-01-01"</span>, <span class="st">"2014-12-31"</span>)))
spw_11_r &lt;-<span class="st"> </span><span class="kw"><a href="../reference/detect_event.html">detect_event</a></span>(<span class="kw"><a href="../reference/ts2clm.html">ts2clm</a></span>(<span class="dt">data =</span> sst_WA, <span class="dt">smoothPercentileWidth =</span> <span class="dv">11</span>,
                                <span class="dt">climatologyPeriod =</span> <span class="kw">c</span>(<span class="st">"1982-01-01"</span>, <span class="st">"2014-12-31"</span>)))
spw_51_r &lt;-<span class="st"> </span><span class="kw"><a href="../reference/detect_event.html">detect_event</a></span>(<span class="kw"><a href="../reference/ts2clm.html">ts2clm</a></span>(<span class="dt">data =</span> sst_WA, <span class="dt">smoothPercentileWidth =</span> <span class="dv">51</span>,
                                <span class="dt">climatologyPeriod =</span> <span class="kw">c</span>(<span class="st">"1982-01-01"</span>, <span class="st">"2014-12-31"</span>)))</code></pre></div>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python"><span class="co"># smoothPercentileWidth = FALSE</span>
mhws, clim <span class="op">=</span> mhw.detect(t, sst, smoothPercentile <span class="op">=</span> <span class="va">False</span>)
mhws_df <span class="op">=</span> pd.DataFrame.from_dict(mhws)
mhws_df.to_csv(<span class="st">'mhws_py_spw_no.csv'</span>, sep <span class="op">=</span> <span class="st">','</span>, index <span class="op">=</span> <span class="va">False</span>)
clim_df <span class="op">=</span> pd.DataFrame.from_dict(clim)
clim_df.to_csv(<span class="st">'clim_py_spw_no.csv'</span>, sep <span class="op">=</span> <span class="st">','</span>, index <span class="op">=</span> <span class="va">False</span>)
<span class="co"># smoothPercentileWidth = 11</span>
mhws, clim <span class="op">=</span> mhw.detect(t, sst, smoothPercentileWidth <span class="op">=</span> <span class="dv">11</span>)
mhws_df <span class="op">=</span> pd.DataFrame.from_dict(mhws)
mhws_df.to_csv(<span class="st">'mhws_py_spw_11.csv'</span>, sep <span class="op">=</span> <span class="st">','</span>, index <span class="op">=</span> <span class="va">False</span>)
clim_df <span class="op">=</span> pd.DataFrame.from_dict(clim)
clim_df.to_csv(<span class="st">'clim_py_spw_11.csv'</span>, sep <span class="op">=</span> <span class="st">','</span>, index <span class="op">=</span> <span class="va">False</span>)
<span class="co"># smoothPercentileWidth = 51</span>
mhws, clim <span class="op">=</span> mhw.detect(t, sst, smoothPercentileWidth <span class="op">=</span> <span class="dv">51</span>)
mhws_df <span class="op">=</span> pd.DataFrame.from_dict(mhws)
mhws_df.to_csv(<span class="st">'mhws_py_spw_51.csv'</span>, sep <span class="op">=</span> <span class="st">','</span>, index <span class="op">=</span> <span class="va">False</span>)
clim_df <span class="op">=</span> pd.DataFrame.from_dict(clim)
clim_df.to_csv(<span class="st">'clim_py_spw_51.csv'</span>, sep <span class="op">=</span> <span class="st">','</span>, index <span class="op">=</span> <span class="va">False</span>)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Load Python</span>
spw_no_py_event &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">"mhws_py_spw_no.csv"</span>)
spw_no_py_clim &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">"clim_py_spw_no.csv"</span>)
spw_11_py_event &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">"mhws_py_spw_11.csv"</span>)
spw_11_py_clim &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">"clim_py_spw_11.csv"</span>)
spw_51_py_event &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">"mhws_py_spw_51.csv"</span>)
spw_51_py_clim &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">"clim_py_spw_51.csv"</span>)

<span class="co"># Compare clims and intensities</span>
<span class="co"># no smoothing</span>
<span class="kw">cor</span>(spw_no_r<span class="op">$</span>climatology<span class="op">$</span>seas, spw_no_py_clim<span class="op">$</span>seas)</code></pre></div>
<pre><code>## [1] 0.9999992</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(spw_no_r<span class="op">$</span>climatology<span class="op">$</span>seas) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(spw_no_py_clim<span class="op">$</span>seas)</code></pre></div>
<pre><code>## [1] -2.061954</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor</span>(spw_no_r<span class="op">$</span>climatology<span class="op">$</span>thresh, spw_no_py_clim<span class="op">$</span>thresh)</code></pre></div>
<pre><code>## [1] 0.9999965</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(spw_no_r<span class="op">$</span>climatology<span class="op">$</span>thresh) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(spw_no_py_clim<span class="op">$</span>thresh)</code></pre></div>
<pre><code>## [1] -6.499</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(spw_no_r<span class="op">$</span>event<span class="op">$</span>intensity_cumulative) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(spw_no_py_event<span class="op">$</span>intensity_cumulative)</code></pre></div>
<pre><code>## [1] 0.1080191</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(spw_no_r<span class="op">$</span>event<span class="op">$</span>intensity_max) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(spw_no_py_event<span class="op">$</span>intensity_max)</code></pre></div>
<pre><code>## [1] 0.01519676</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># 11 days</span>
<span class="kw">cor</span>(spw_11_r<span class="op">$</span>climatology<span class="op">$</span>seas, spw_11_py_clim<span class="op">$</span>seas)</code></pre></div>
<pre><code>## [1] 0.9999997</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(spw_11_r<span class="op">$</span>climatology<span class="op">$</span>seas) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(spw_11_py_clim<span class="op">$</span>seas)</code></pre></div>
<pre><code>## [1] -1.99972</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor</span>(spw_11_r<span class="op">$</span>climatology<span class="op">$</span>thresh, spw_11_py_clim<span class="op">$</span>thresh)</code></pre></div>
<pre><code>## [1] 0.999999</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(spw_11_r<span class="op">$</span>climatology<span class="op">$</span>thresh) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(spw_11_py_clim<span class="op">$</span>thresh)</code></pre></div>
<pre><code>## [1] -6.317182</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(spw_11_r<span class="op">$</span>event<span class="op">$</span>intensity_cumulative) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(spw_11_py_event<span class="op">$</span>intensity_cumulative)</code></pre></div>
<pre><code>## [1] 0.1191614</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(spw_11_r<span class="op">$</span>event<span class="op">$</span>intensity_max) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(spw_11_py_event<span class="op">$</span>intensity_max)</code></pre></div>
<pre><code>## [1] 0.005962097</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># 51 days</span>
<span class="kw">cor</span>(spw_51_r<span class="op">$</span>climatology<span class="op">$</span>seas, spw_51_py_clim<span class="op">$</span>seas)</code></pre></div>
<pre><code>## [1] 0.9999999</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(spw_51_r<span class="op">$</span>climatology<span class="op">$</span>seas) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(spw_51_py_clim<span class="op">$</span>seas)</code></pre></div>
<pre><code>## [1] -1.97723</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor</span>(spw_51_r<span class="op">$</span>climatology<span class="op">$</span>thresh, spw_51_py_clim<span class="op">$</span>thresh)</code></pre></div>
<pre><code>## [1] 0.9999998</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(spw_51_r<span class="op">$</span>climatology<span class="op">$</span>thresh) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(spw_51_py_clim<span class="op">$</span>thresh)</code></pre></div>
<pre><code>## [1] -6.616647</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(spw_51_r<span class="op">$</span>event<span class="op">$</span>intensity_cumulative) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(spw_51_py_event<span class="op">$</span>intensity_cumulative)</code></pre></div>
<pre><code>## [1] 0.1498496</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(spw_51_r<span class="op">$</span>event<span class="op">$</span>intensity_max) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(spw_51_py_event<span class="op">$</span>intensity_max)</code></pre></div>
<pre><code>## [1] 0.006400502</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Compare events</span>
spw_no_event &lt;-<span class="st"> </span><span class="kw">compare_event</span>(spw_no_r<span class="op">$</span>event, spw_no_py_event)
spw_no_event</code></pre></div>
<pre><code>##            r                            var
## 1         NA                       event_no
## 2  1.0000000                    index_start
## 3  1.0000000                     index_peak
## 4  1.0000000                      index_end
## 5  1.0000000                       duration
## 6  0.9999980                 intensity_mean
## 7  0.9999992                  intensity_max
## 8  0.9993830                  intensity_var
## 9  0.9999999           intensity_cumulative
## 10 0.9999956       intensity_mean_relThresh
## 11 0.9997743        intensity_max_relThresh
## 12 0.9993297        intensity_var_relThresh
## 13 0.9999995 intensity_cumulative_relThresh
## 14 1.0000000             intensity_mean_abs
## 15 0.9989767              intensity_max_abs
## 16 0.9995816              intensity_var_abs
## 17 1.0000000       intensity_cumulative_abs
## 18 0.9999992                     rate_onset
## 19 0.9999995                   rate_decline</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">spw_11_event &lt;-<span class="st"> </span><span class="kw">compare_event</span>(spw_11_r<span class="op">$</span>event, spw_11_py_event)
spw_11_event</code></pre></div>
<pre><code>##            r                            var
## 1         NA                       event_no
## 2  1.0000000                    index_start
## 3  1.0000000                     index_peak
## 4  1.0000000                      index_end
## 5  1.0000000                       duration
## 6  0.9999983                 intensity_mean
## 7  0.9999994                  intensity_max
## 8  0.9994326                  intensity_var
## 9  0.9999999           intensity_cumulative
## 10 0.9999963       intensity_mean_relThresh
## 11 0.9999580        intensity_max_relThresh
## 12 0.9994217        intensity_var_relThresh
## 13 0.9999996 intensity_cumulative_relThresh
## 14 1.0000000             intensity_mean_abs
## 15 0.9989804              intensity_max_abs
## 16 0.9996101              intensity_var_abs
## 17 1.0000000       intensity_cumulative_abs
## 18 0.9999985                     rate_onset
## 19 0.9999995                   rate_decline</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">spw_51_event &lt;-<span class="st"> </span><span class="kw">compare_event</span>(spw_51_r<span class="op">$</span>event, spw_51_py_event)
spw_51_event</code></pre></div>
<pre><code>##            r                            var
## 1         NA                       event_no
## 2  1.0000000                    index_start
## 3  1.0000000                     index_peak
## 4  1.0000000                      index_end
## 5  1.0000000                       duration
## 6  0.9999995                 intensity_mean
## 7  0.9999999                  intensity_max
## 8  0.9996566                  intensity_var
## 9  1.0000000           intensity_cumulative
## 10 0.9999969       intensity_mean_relThresh
## 11 0.9999678        intensity_max_relThresh
## 12 0.9996305        intensity_var_relThresh
## 13 0.9999996 intensity_cumulative_relThresh
## 14 1.0000000             intensity_mean_abs
## 15 0.9992145              intensity_max_abs
## 16 0.9997404              intensity_var_abs
## 17 1.0000000       intensity_cumulative_abs
## 18 1.0000000                     rate_onset
## 19 1.0000000                   rate_decline</code></pre>
<p>Surprisingly the smoothing window, regardless if it is applied or not, seems to make little difference. But again, let’s compare the old R code against Python as well.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ts &lt;-<span class="st"> </span>RmarineHeatWaves<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/RmarineHeatWaves/topics/make_whole">make_whole</a></span>(sst_WA)
spw_no_r_old &lt;-<span class="st"> </span>RmarineHeatWaves<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/RmarineHeatWaves/topics/detect">detect</a></span>(<span class="dt">data =</span> ts, <span class="dt">climatology_start =</span> <span class="dv">1982</span>, <span class="dt">climatology_end =</span> <span class="dv">2014</span>, <span class="dt">smooth_percentile =</span> <span class="ot">FALSE</span>)
spw_no_r_old_event &lt;-<span class="st"> </span>spw_no_r_old<span class="op">$</span>event
spw_no_r_old_clim &lt;-<span class="st"> </span>spw_no_r_old<span class="op">$</span>clim

<span class="co"># Compare new and old R code</span>
<span class="kw">sum</span>(spw_no_r<span class="op">$</span>climatology<span class="op">$</span>seas) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(spw_no_r_old_clim<span class="op">$</span>seas_clim_year)</code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(spw_no_r<span class="op">$</span>climatology<span class="op">$</span>thresh) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(spw_no_r_old_clim<span class="op">$</span>thresh_clim_year)</code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Compare old &amp; new R against Python</span>
<span class="kw">sum</span>(spw_no_py_clim<span class="op">$</span>seas) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(spw_no_r_old_clim<span class="op">$</span>seas_clim_year)</code></pre></div>
<pre><code>## [1] 2.061954</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(spw_no_py_clim<span class="op">$</span>seas) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(spw_no_r<span class="op">$</span>climatology<span class="op">$</span>seas)</code></pre></div>
<pre><code>## [1] 2.061954</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(spw_no_py_clim<span class="op">$</span>thresh) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(spw_no_r_old_clim<span class="op">$</span>thresh_clim_year)</code></pre></div>
<pre><code>## [1] 6.499</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(spw_no_py_clim<span class="op">$</span>thresh) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(spw_no_r<span class="op">$</span>climatology<span class="op">$</span>thresh)</code></pre></div>
<pre><code>## [1] 6.499</code></pre>
</div>
<div id="windowhalfwidth-comparisons" class="section level2">
<h2 class="hasAnchor">
<a href="#windowhalfwidth-comparisons" class="anchor"></a><code>windowHalfWidth</code> comparisons</h2>
<p>We’ve now seen that the differences between both the new &amp; old R code and the Python code hold consistently different regardless of the changing of the <code>pctile</code> or <code>smoothWindowPercentile</code>. This then leads me to think that this is just a rounding issue between the two languages, and that there is not some fundamentally different calculation happening somewhere in the code. That being said, it is still necessary to be thorough and so I’ll go through the rest of the arguments now. Starting with <code>windowHalfWidth</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">whw_3_r &lt;-<span class="st"> </span><span class="kw"><a href="../reference/detect_event.html">detect_event</a></span>(<span class="kw"><a href="../reference/ts2clm.html">ts2clm</a></span>(<span class="dt">data =</span> sst_WA, <span class="dt">windowHalfWidth =</span> <span class="dv">3</span>,
                               <span class="dt">climatologyPeriod =</span> <span class="kw">c</span>(<span class="st">"1982-01-01"</span>, <span class="st">"2014-12-31"</span>)))
whw_7_r &lt;-<span class="st"> </span><span class="kw"><a href="../reference/detect_event.html">detect_event</a></span>(<span class="kw"><a href="../reference/ts2clm.html">ts2clm</a></span>(<span class="dt">data =</span> sst_WA, <span class="dt">windowHalfWidth =</span> <span class="dv">7</span>,
                               <span class="dt">climatologyPeriod =</span> <span class="kw">c</span>(<span class="st">"1982-01-01"</span>, <span class="st">"2014-12-31"</span>)))</code></pre></div>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python"><span class="co"># windowHalfWidth = 3</span>
mhws, clim <span class="op">=</span> mhw.detect(t, sst, windowHalfWidth <span class="op">=</span> <span class="dv">3</span>)
mhws_df <span class="op">=</span> pd.DataFrame.from_dict(mhws)
mhws_df.to_csv(<span class="st">'mhws_py_whw_3.csv'</span>, sep <span class="op">=</span> <span class="st">','</span>, index <span class="op">=</span> <span class="va">False</span>)
clim_df <span class="op">=</span> pd.DataFrame.from_dict(clim)
clim_df.to_csv(<span class="st">'clim_py_whw_3.csv'</span>, sep <span class="op">=</span> <span class="st">','</span>, index <span class="op">=</span> <span class="va">False</span>)
<span class="co"># windowHalfWidth = 7</span>
mhws, clim <span class="op">=</span> mhw.detect(t, sst, windowHalfWidth <span class="op">=</span> <span class="dv">7</span>)
mhws_df <span class="op">=</span> pd.DataFrame.from_dict(mhws)
mhws_df.to_csv(<span class="st">'mhws_py_whw_7.csv'</span>, sep <span class="op">=</span> <span class="st">','</span>, index <span class="op">=</span> <span class="va">False</span>)
clim_df <span class="op">=</span> pd.DataFrame.from_dict(clim)
clim_df.to_csv(<span class="st">'clim_py_whw_7.csv'</span>, sep <span class="op">=</span> <span class="st">','</span>, index <span class="op">=</span> <span class="va">False</span>)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Load Python</span>
whw_3_py_event &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">"mhws_py_whw_3.csv"</span>)
whw_3_py_clim &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">"clim_py_whw_3.csv"</span>)
whw_7_py_event &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">"mhws_py_whw_7.csv"</span>)
whw_7_py_clim &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">"clim_py_whw_7.csv"</span>)

<span class="co"># Compare clims and intensities</span>
<span class="co"># 3 days</span>
<span class="kw">cor</span>(whw_3_r<span class="op">$</span>climatology<span class="op">$</span>seas, whw_3_py_clim<span class="op">$</span>seas)</code></pre></div>
<pre><code>## [1] 0.9999999</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(whw_3_r<span class="op">$</span>climatology<span class="op">$</span>seas) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(whw_3_py_clim<span class="op">$</span>seas)</code></pre></div>
<pre><code>## [1] -1.239599</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor</span>(whw_3_r<span class="op">$</span>climatology<span class="op">$</span>thresh, whw_3_py_clim<span class="op">$</span>thresh)</code></pre></div>
<pre><code>## [1] 0.9999999</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(whw_3_r<span class="op">$</span>climatology<span class="op">$</span>thresh) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(whw_3_py_clim<span class="op">$</span>thresh)</code></pre></div>
<pre><code>## [1] -3.037484</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(whw_3_r<span class="op">$</span>event<span class="op">$</span>intensity_cumulative) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(whw_3_py_event<span class="op">$</span>intensity_cumulative)</code></pre></div>
<pre><code>## [1] 0.1001013</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(whw_3_r<span class="op">$</span>event<span class="op">$</span>intensity_max) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(whw_3_py_event<span class="op">$</span>intensity_max)</code></pre></div>
<pre><code>## [1] 0.005394135</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># 7 days</span>
<span class="kw">cor</span>(whw_7_r<span class="op">$</span>climatology<span class="op">$</span>seas, whw_7_py_clim<span class="op">$</span>seas)</code></pre></div>
<pre><code>## [1] 0.9999998</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(whw_7_r<span class="op">$</span>climatology<span class="op">$</span>seas) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(whw_7_py_clim<span class="op">$</span>seas)</code></pre></div>
<pre><code>## [1] -2.796456</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor</span>(whw_7_r<span class="op">$</span>climatology<span class="op">$</span>thresh, whw_7_py_clim<span class="op">$</span>thresh)</code></pre></div>
<pre><code>## [1] 0.999998</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(whw_7_r<span class="op">$</span>climatology<span class="op">$</span>thresh) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(whw_7_py_clim<span class="op">$</span>thresh)</code></pre></div>
<pre><code>## [1] -13.58655</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(whw_7_r<span class="op">$</span>event<span class="op">$</span>intensity_cumulative) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(whw_7_py_event<span class="op">$</span>intensity_cumulative)</code></pre></div>
<pre><code>## [1] 8.298912</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(whw_7_r<span class="op">$</span>event<span class="op">$</span>intensity_max) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(whw_7_py_event<span class="op">$</span>intensity_max)</code></pre></div>
<pre><code>## [1] 1.901123</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Compare events</span>
whw_3_event &lt;-<span class="st"> </span><span class="kw">compare_event</span>(whw_3_r<span class="op">$</span>event, whw_3_py_event)
whw_3_event</code></pre></div>
<pre><code>##            r                            var
## 1         NA                       event_no
## 2  1.0000000                    index_start
## 3  1.0000000                     index_peak
## 4  1.0000000                      index_end
## 5  1.0000000                       duration
## 6  0.9999996                 intensity_mean
## 7  0.9999999                  intensity_max
## 8  0.9996481                  intensity_var
## 9  1.0000000           intensity_cumulative
## 10 0.9999993       intensity_mean_relThresh
## 11 0.9999937        intensity_max_relThresh
## 12 0.9996044        intensity_var_relThresh
## 13 0.9999999 intensity_cumulative_relThresh
## 14 1.0000000             intensity_mean_abs
## 15 0.9993263              intensity_max_abs
## 16 0.9997487              intensity_var_abs
## 17 1.0000000       intensity_cumulative_abs
## 18 1.0000000                     rate_onset
## 19 1.0000000                   rate_decline</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># whw_7_event &lt;- compare_event(whw_7_r$event, whw_7_py_event)</span>
<span class="co"># whw_7_event</span></code></pre></div>
<p>We see here that the <code>windowHalfWidth</code> has a large effect on the difference between the results than anything else so far. The difference per row is still low at ~0.001 so isn’t much cause for alarm. We do however detect a different number of events if <code>windowHalfWidth = 7</code>. Let’s see how they differ.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">whw_7_r_event &lt;-<span class="st"> </span>whw_7_r<span class="op">$</span>event
whw_7_r_event<span class="op">$</span>date_start[<span class="op">!</span>whw_7_r_event<span class="op">$</span>date_start <span class="op">%in%</span><span class="st"> </span>whw_7_py_event<span class="op">$</span>date_start]</code></pre></div>
<pre><code>## [1] "2006-03-05"</code></pre>
<p>The difference lies in the R code detecting a five day event that the Python code must have seen as only 4 days or less. Again due to very narrow differences in the threshold values.</p>
<p>Let’s look if there is a difference between the old and new R code.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ts &lt;-<span class="st"> </span>RmarineHeatWaves<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/RmarineHeatWaves/topics/make_whole">make_whole</a></span>(sst_WA)
whw_7_r_old &lt;-<span class="st"> </span>RmarineHeatWaves<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/RmarineHeatWaves/topics/detect">detect</a></span>(<span class="dt">data =</span> ts, <span class="dt">climatology_start =</span> <span class="dv">1982</span>, <span class="dt">climatology_end =</span> <span class="dv">2014</span>, <span class="dt">window_half_width =</span> <span class="dv">7</span>)

<span class="co"># Compare new and old R code</span>
<span class="kw">sum</span>(whw_7_r<span class="op">$</span>climatology<span class="op">$</span>seas) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(whw_7_r_old<span class="op">$</span>clim<span class="op">$</span>seas_clim_year)</code></pre></div>
<pre><code>## [1] -2.910383e-11</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(whw_7_r<span class="op">$</span>climatology<span class="op">$</span>thresh) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(whw_7_r_old<span class="op">$</span>clim<span class="op">$</span>thresh_clim_year)</code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(whw_7_r<span class="op">$</span>event<span class="op">$</span>intensity_cumulative) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(whw_7_r_old<span class="op">$</span>event<span class="op">$</span>int_cum)</code></pre></div>
<pre><code>## [1] 4.547474e-13</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(whw_7_r<span class="op">$</span>event<span class="op">$</span>intensity_max) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(whw_7_r_old<span class="op">$</span>event<span class="op">$</span>int_max)</code></pre></div>
<pre><code>## [1] 2.842171e-14</code></pre>
<p>Everything matches up between old and new R for <code>windowHalfWidth = 7</code>.</p>
</div>
<div id="minduration-comparisons" class="section level2">
<h2 class="hasAnchor">
<a href="#minduration-comparisons" class="anchor"></a><code>minDuration</code> comparisons</h2>
<p>Now we move away form the arguments that effect the climatology calculations, and focus just on those that determine the classification of events.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">minD_3_r &lt;-<span class="st"> </span><span class="kw"><a href="../reference/detect_event.html">detect_event</a></span>(<span class="kw"><a href="../reference/ts2clm.html">ts2clm</a></span>(<span class="dt">data =</span> sst_WA, <span class="dt">climatologyPeriod =</span> <span class="kw">c</span>(<span class="st">"1982-01-01"</span>, <span class="st">"2014-12-31"</span>)), 
                         <span class="dt">minDuration =</span> <span class="dv">3</span>)
minD_7_r &lt;-<span class="st"> </span><span class="kw"><a href="../reference/detect_event.html">detect_event</a></span>(<span class="kw"><a href="../reference/ts2clm.html">ts2clm</a></span>(<span class="dt">data =</span> sst_WA, <span class="dt">climatologyPeriod =</span> <span class="kw">c</span>(<span class="st">"1982-01-01"</span>, <span class="st">"2014-12-31"</span>)), 
                         <span class="dt">minDuration =</span> <span class="dv">7</span>)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python"><span class="co"># minDuration = 3</span>
mhws, clim <span class="op">=</span> mhw.detect(t, sst, minDuration <span class="op">=</span> <span class="dv">3</span>)
mhws_df <span class="op">=</span> pd.DataFrame.from_dict(mhws)
mhws_df.to_csv(<span class="st">'mhws_py_minD_3.csv'</span>, sep <span class="op">=</span> <span class="st">','</span>, index <span class="op">=</span> <span class="va">False</span>)
clim_df <span class="op">=</span> pd.DataFrame.from_dict(clim)
clim_df.to_csv(<span class="st">'clim_py_minD_3.csv'</span>, sep <span class="op">=</span> <span class="st">','</span>, index <span class="op">=</span> <span class="va">False</span>)
<span class="co"># minDuration = 7</span>
mhws, clim <span class="op">=</span> mhw.detect(t, sst, minDuration <span class="op">=</span> <span class="dv">7</span>)
mhws_df <span class="op">=</span> pd.DataFrame.from_dict(mhws)
mhws_df.to_csv(<span class="st">'mhws_py_minD_7.csv'</span>, sep <span class="op">=</span> <span class="st">','</span>, index <span class="op">=</span> <span class="va">False</span>)
clim_df <span class="op">=</span> pd.DataFrame.from_dict(clim)
clim_df.to_csv(<span class="st">'clim_py_minD_7.csv'</span>, sep <span class="op">=</span> <span class="st">','</span>, index <span class="op">=</span> <span class="va">False</span>)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Load Python</span>
minD_3_py_event &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">"mhws_py_minD_3.csv"</span>)
minD_3_py_clim &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">"clim_py_minD_3.csv"</span>)
minD_7_py_event &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">"mhws_py_minD_7.csv"</span>)
minD_7_py_clim &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">"clim_py_minD_7.csv"</span>)

<span class="co"># Compare clims and intensities</span>
<span class="co"># 3 days</span>
<span class="kw">cor</span>(minD_3_r<span class="op">$</span>climatology<span class="op">$</span>seas, minD_3_py_clim<span class="op">$</span>seas)</code></pre></div>
<pre><code>## [1] 0.9999999</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(minD_3_r<span class="op">$</span>climatology<span class="op">$</span>seas) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(minD_3_py_clim<span class="op">$</span>seas)</code></pre></div>
<pre><code>## [1] -1.98122</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor</span>(minD_3_r<span class="op">$</span>climatology<span class="op">$</span>thresh, minD_3_py_clim<span class="op">$</span>thresh)</code></pre></div>
<pre><code>## [1] 0.9999996</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(minD_3_r<span class="op">$</span>climatology<span class="op">$</span>thresh) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(minD_3_py_clim<span class="op">$</span>thresh)</code></pre></div>
<pre><code>## [1] -6.563516</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(minD_3_r<span class="op">$</span>event<span class="op">$</span>intensity_cumulative) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(minD_3_py_event<span class="op">$</span>intensity_cumulative)</code></pre></div>
<pre><code>## [1] 0.1896852</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(minD_3_r<span class="op">$</span>event<span class="op">$</span>intensity_max) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(minD_3_py_event<span class="op">$</span>intensity_max)</code></pre></div>
<pre><code>## [1] 0.01326261</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># 7 days</span>
<span class="kw">cor</span>(minD_7_r<span class="op">$</span>climatology<span class="op">$</span>seas, minD_7_py_clim<span class="op">$</span>seas)</code></pre></div>
<pre><code>## [1] 0.9999999</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(minD_7_r<span class="op">$</span>climatology<span class="op">$</span>seas) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(minD_7_py_clim<span class="op">$</span>seas)</code></pre></div>
<pre><code>## [1] -1.98122</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor</span>(minD_7_r<span class="op">$</span>climatology<span class="op">$</span>thresh, minD_7_py_clim<span class="op">$</span>thresh)</code></pre></div>
<pre><code>## [1] 0.9999996</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(minD_7_r<span class="op">$</span>climatology<span class="op">$</span>thresh) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(minD_7_py_clim<span class="op">$</span>thresh)</code></pre></div>
<pre><code>## [1] -6.563516</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(minD_7_r<span class="op">$</span>event<span class="op">$</span>intensity_cumulative) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(minD_7_py_event<span class="op">$</span>intensity_cumulative)</code></pre></div>
<pre><code>## [1] 0.1119377</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(minD_7_r<span class="op">$</span>event<span class="op">$</span>intensity_max) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(minD_7_py_event<span class="op">$</span>intensity_max)</code></pre></div>
<pre><code>## [1] 0.007003591</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Compare events</span>
minD_3_event &lt;-<span class="st"> </span><span class="kw">compare_event</span>(minD_3_r<span class="op">$</span>event, minD_3_py_event)
minD_3_event</code></pre></div>
<pre><code>##            r                            var
## 1         NA                       event_no
## 2  1.0000000                    index_start
## 3  1.0000000                     index_peak
## 4  1.0000000                      index_end
## 5  1.0000000                       duration
## 6  0.9999988                 intensity_mean
## 7  0.9999997                  intensity_max
## 8  0.9987983                  intensity_var
## 9  1.0000000           intensity_cumulative
## 10 0.9999894       intensity_mean_relThresh
## 11 0.9999946        intensity_max_relThresh
## 12 0.9987097        intensity_var_relThresh
## 13 0.9999996 intensity_cumulative_relThresh
## 14 1.0000000             intensity_mean_abs
## 15 0.9991713              intensity_max_abs
## 16 0.9990272              intensity_var_abs
## 17 1.0000000       intensity_cumulative_abs
## 18 1.0000000                     rate_onset
## 19 0.9999999                   rate_decline</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">minD_7_event &lt;-<span class="st"> </span><span class="kw">compare_event</span>(minD_7_r<span class="op">$</span>event, minD_7_py_event)
minD_7_event</code></pre></div>
<pre><code>##            r                            var
## 1         NA                       event_no
## 2  1.0000000                    index_start
## 3  1.0000000                     index_peak
## 4  1.0000000                      index_end
## 5  1.0000000                       duration
## 6  0.9999992                 intensity_mean
## 7  0.9999997                  intensity_max
## 8  0.9992868                  intensity_var
## 9  1.0000000           intensity_cumulative
## 10 0.9999965       intensity_mean_relThresh
## 11 0.9999769        intensity_max_relThresh
## 12 0.9992401        intensity_var_relThresh
## 13 0.9999995 intensity_cumulative_relThresh
## 14 1.0000000             intensity_mean_abs
## 15 0.9996425              intensity_max_abs
## 16 0.9994580              intensity_var_abs
## 17 1.0000000       intensity_cumulative_abs
## 18 0.9999999                     rate_onset
## 19 0.9999999                   rate_decline</code></pre>
<p>As expected, changing the minimum duration of events has no effect on the threshold calculations. It is however gratifying to see that the same number of events is calculated between languages, regardless of the minimum duration. The difference these cause in the intensities of the events is also negligible between languages.</p>
</div>
<div id="joinacrossgaps-comparisons" class="section level2">
<h2 class="hasAnchor">
<a href="#joinacrossgaps-comparisons" class="anchor"></a><code>joinAcrossGaps</code> comparisons</h2>
<p>Now for the final argument in the base functionality. This too should not effect the climatologies. Only the events.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">joinAG_no_r &lt;-<span class="st"> </span><span class="kw"><a href="../reference/detect_event.html">detect_event</a></span>(<span class="kw"><a href="../reference/ts2clm.html">ts2clm</a></span>(<span class="dt">data =</span> sst_WA, <span class="dt">climatologyPeriod =</span> <span class="kw">c</span>(<span class="st">"1982-01-01"</span>, <span class="st">"2014-12-31"</span>)), 
                            <span class="dt">joinAcrossGaps =</span> <span class="ot">FALSE</span>)
joinAG_1_r &lt;-<span class="st"> </span><span class="kw"><a href="../reference/detect_event.html">detect_event</a></span>(<span class="kw"><a href="../reference/ts2clm.html">ts2clm</a></span>(<span class="dt">data =</span> sst_WA, <span class="dt">climatologyPeriod =</span> <span class="kw">c</span>(<span class="st">"1982-01-01"</span>, <span class="st">"2014-12-31"</span>)), 
                           <span class="dt">maxGap =</span> <span class="dv">1</span>)
joinAG_5_r &lt;-<span class="st"> </span><span class="kw"><a href="../reference/detect_event.html">detect_event</a></span>(<span class="kw"><a href="../reference/ts2clm.html">ts2clm</a></span>(<span class="dt">data =</span> sst_WA, <span class="dt">climatologyPeriod =</span> <span class="kw">c</span>(<span class="st">"1982-01-01"</span>, <span class="st">"2014-12-31"</span>)), 
                           <span class="dt">maxGap =</span> <span class="dv">5</span>)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python"><span class="co"># joinAGuration = False</span>
mhws, clim <span class="op">=</span> mhw.detect(t, sst, joinAcrossGaps <span class="op">=</span> <span class="va">False</span>)
mhws_df <span class="op">=</span> pd.DataFrame.from_dict(mhws)
mhws_df.to_csv(<span class="st">'mhws_py_joinAG_no.csv'</span>, sep <span class="op">=</span> <span class="st">','</span>, index <span class="op">=</span> <span class="va">False</span>)
clim_df <span class="op">=</span> pd.DataFrame.from_dict(clim)
clim_df.to_csv(<span class="st">'clim_py_joinAG_no.csv'</span>, sep <span class="op">=</span> <span class="st">','</span>, index <span class="op">=</span> <span class="va">False</span>)
<span class="co"># maxGap = 1</span>
mhws, clim <span class="op">=</span> mhw.detect(t, sst, maxGap <span class="op">=</span> <span class="dv">1</span>)
mhws_df <span class="op">=</span> pd.DataFrame.from_dict(mhws)
mhws_df.to_csv(<span class="st">'mhws_py_joinAG_1.csv'</span>, sep <span class="op">=</span> <span class="st">','</span>, index <span class="op">=</span> <span class="va">False</span>)
clim_df <span class="op">=</span> pd.DataFrame.from_dict(clim)
clim_df.to_csv(<span class="st">'clim_py_joinAG_1.csv'</span>, sep <span class="op">=</span> <span class="st">','</span>, index <span class="op">=</span> <span class="va">False</span>)
<span class="co"># maxGap = 5</span>
mhws, clim <span class="op">=</span> mhw.detect(t, sst, maxGap <span class="op">=</span> <span class="dv">5</span>)
mhws_df <span class="op">=</span> pd.DataFrame.from_dict(mhws)
mhws_df.to_csv(<span class="st">'mhws_py_joinAG_5.csv'</span>, sep <span class="op">=</span> <span class="st">','</span>, index <span class="op">=</span> <span class="va">False</span>)
clim_df <span class="op">=</span> pd.DataFrame.from_dict(clim)
clim_df.to_csv(<span class="st">'clim_py_joinAG_5.csv'</span>, sep <span class="op">=</span> <span class="st">','</span>, index <span class="op">=</span> <span class="va">False</span>)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Load Python</span>
joinAG_no_py_event &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">"mhws_py_joinAG_no.csv"</span>)
joinAG_no_py_clim &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">"clim_py_joinAG_no.csv"</span>)
joinAG_1_py_event &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">"mhws_py_joinAG_1.csv"</span>)
joinAG_1_py_clim &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">"clim_py_joinAG_1.csv"</span>)
joinAG_5_py_event &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">"mhws_py_joinAG_5.csv"</span>)
joinAG_5_py_clim &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">"clim_py_joinAG_5.csv"</span>)

<span class="co"># Compare clims and intensities</span>
<span class="co"># no days</span>
<span class="kw">cor</span>(joinAG_no_r<span class="op">$</span>climatology<span class="op">$</span>seas, joinAG_no_py_clim<span class="op">$</span>seas)</code></pre></div>
<pre><code>## [1] 0.9999999</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(joinAG_no_r<span class="op">$</span>climatology<span class="op">$</span>seas) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(joinAG_no_py_clim<span class="op">$</span>seas)</code></pre></div>
<pre><code>## [1] -1.98122</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor</span>(joinAG_no_r<span class="op">$</span>climatology<span class="op">$</span>thresh, joinAG_no_py_clim<span class="op">$</span>thresh)</code></pre></div>
<pre><code>## [1] 0.9999996</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(joinAG_no_r<span class="op">$</span>climatology<span class="op">$</span>thresh) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(joinAG_no_py_clim<span class="op">$</span>thresh)</code></pre></div>
<pre><code>## [1] -6.563516</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(joinAG_no_r<span class="op">$</span>event<span class="op">$</span>intensity_cumulative) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(joinAG_no_py_event<span class="op">$</span>intensity_cumulative)</code></pre></div>
<pre><code>## [1] 0.1503818</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(joinAG_no_r<span class="op">$</span>event<span class="op">$</span>intensity_max) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(joinAG_no_py_event<span class="op">$</span>intensity_max)</code></pre></div>
<pre><code>## [1] 0.01419052</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># 1 day</span>
<span class="kw">cor</span>(joinAG_1_r<span class="op">$</span>climatology<span class="op">$</span>seas, joinAG_1_py_clim<span class="op">$</span>seas)</code></pre></div>
<pre><code>## [1] 0.9999999</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(joinAG_1_r<span class="op">$</span>climatology<span class="op">$</span>seas) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(joinAG_1_py_clim<span class="op">$</span>seas)</code></pre></div>
<pre><code>## [1] -1.98122</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor</span>(joinAG_1_r<span class="op">$</span>climatology<span class="op">$</span>thresh, joinAG_1_py_clim<span class="op">$</span>thresh)</code></pre></div>
<pre><code>## [1] 0.9999996</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(joinAG_1_r<span class="op">$</span>climatology<span class="op">$</span>thresh) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(joinAG_1_py_clim<span class="op">$</span>thresh)</code></pre></div>
<pre><code>## [1] -6.563516</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(joinAG_1_r<span class="op">$</span>event<span class="op">$</span>intensity_cumulative) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(joinAG_1_py_event<span class="op">$</span>intensity_cumulative)</code></pre></div>
<pre><code>## [1] 0.1527155</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(joinAG_1_r<span class="op">$</span>event<span class="op">$</span>intensity_max) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(joinAG_1_py_event<span class="op">$</span>intensity_max)</code></pre></div>
<pre><code>## [1] 0.01185678</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># 7 days</span>
<span class="kw">cor</span>(joinAG_5_r<span class="op">$</span>climatology<span class="op">$</span>seas, joinAG_5_py_clim<span class="op">$</span>seas)</code></pre></div>
<pre><code>## [1] 0.9999999</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(joinAG_5_r<span class="op">$</span>climatology<span class="op">$</span>seas) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(joinAG_5_py_clim<span class="op">$</span>seas)</code></pre></div>
<pre><code>## [1] -1.98122</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor</span>(joinAG_5_r<span class="op">$</span>climatology<span class="op">$</span>thresh, joinAG_5_py_clim<span class="op">$</span>thresh)</code></pre></div>
<pre><code>## [1] 0.9999996</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(joinAG_5_r<span class="op">$</span>climatology<span class="op">$</span>thresh) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(joinAG_5_py_clim<span class="op">$</span>thresh)</code></pre></div>
<pre><code>## [1] -6.563516</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(joinAG_5_r<span class="op">$</span>event<span class="op">$</span>intensity_cumulative) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(joinAG_5_py_event<span class="op">$</span>intensity_cumulative)</code></pre></div>
<pre><code>## [1] 0.155353</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(joinAG_5_r<span class="op">$</span>event<span class="op">$</span>intensity_max) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(joinAG_5_py_event<span class="op">$</span>intensity_max)</code></pre></div>
<pre><code>## [1] 0.008520925</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Compare events</span>
joinAG_no_event &lt;-<span class="st"> </span><span class="kw">compare_event</span>(joinAG_no_r<span class="op">$</span>event, joinAG_no_py_event)
joinAG_no_event</code></pre></div>
<pre><code>##            r                            var
## 1         NA                       event_no
## 2  1.0000000                    index_start
## 3  1.0000000                     index_peak
## 4  1.0000000                      index_end
## 5  1.0000000                       duration
## 6  0.9999989                 intensity_mean
## 7  0.9999997                  intensity_max
## 8  0.9989915                  intensity_var
## 9  1.0000000           intensity_cumulative
## 10 0.9999972       intensity_mean_relThresh
## 11 0.9999993        intensity_max_relThresh
## 12 0.9989421        intensity_var_relThresh
## 13 0.9999996 intensity_cumulative_relThresh
## 14 1.0000000             intensity_mean_abs
## 15 0.9997855              intensity_max_abs
## 16 0.9992310              intensity_var_abs
## 17 1.0000000       intensity_cumulative_abs
## 18 0.9999999                     rate_onset
## 19 0.9999999                   rate_decline</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">joinAG_1_event &lt;-<span class="st"> </span><span class="kw">compare_event</span>(joinAG_1_r<span class="op">$</span>event, joinAG_1_py_event)
joinAG_1_event</code></pre></div>
<pre><code>##            r                            var
## 1         NA                       event_no
## 2  1.0000000                    index_start
## 3  1.0000000                     index_peak
## 4  1.0000000                      index_end
## 5  1.0000000                       duration
## 6  0.9999991                 intensity_mean
## 7  0.9999997                  intensity_max
## 8  0.9992941                  intensity_var
## 9  1.0000000           intensity_cumulative
## 10 0.9999971       intensity_mean_relThresh
## 11 0.9999832        intensity_max_relThresh
## 12 0.9992455        intensity_var_relThresh
## 13 0.9999996 intensity_cumulative_relThresh
## 14 1.0000000             intensity_mean_abs
## 15 0.9997788              intensity_max_abs
## 16 0.9995172              intensity_var_abs
## 17 1.0000000       intensity_cumulative_abs
## 18 0.9999999                     rate_onset
## 19 0.9999999                   rate_decline</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">joinAG_5_event &lt;-<span class="st"> </span><span class="kw">compare_event</span>(joinAG_5_r<span class="op">$</span>event, joinAG_5_py_event)
joinAG_5_event</code></pre></div>
<pre><code>##            r                            var
## 1         NA                       event_no
## 2  1.0000000                    index_start
## 3  1.0000000                     index_peak
## 4  1.0000000                      index_end
## 5  1.0000000                       duration
## 6  0.9999990                 intensity_mean
## 7  0.9999997                  intensity_max
## 8  0.9995553                  intensity_var
## 9  1.0000000           intensity_cumulative
## 10 0.9999960       intensity_mean_relThresh
## 11 0.9999993        intensity_max_relThresh
## 12 0.9995224        intensity_var_relThresh
## 13 0.9999995 intensity_cumulative_relThresh
## 14 1.0000000             intensity_mean_abs
## 15 0.9966753              intensity_max_abs
## 16 0.9997828              intensity_var_abs
## 17 1.0000000       intensity_cumulative_abs
## 18 1.0000000                     rate_onset
## 19 0.9999999                   rate_decline</code></pre>
<p>A little surprising, but good to see, is that the length of gap between events does not cause a different number of events to be calculated between languages considering all other arguments are kept at the default.</p>
</div>
<div id="conclusion" class="section level2">
<h2 class="hasAnchor">
<a href="#conclusion" class="anchor"></a>Conclusion</h2>
<p>It appears as though, down to a very small degree, there are differences between the outputs of the two languages. That being said, these differences appear to be due to the rounding differences that exist between the languages and so it is not a fault of the code in either, nor are there fundamentally different processes being employed to make the calculations. Indeed, though minute differences may be found in the calculations of the seasonal and threshold climatologies, these differences are consistent. They do not vary. They may change in magnitude depending on the arguments supplied, but these differences never become larger than ~0.001 per row, which has been deemed here as acceptable. Interestingly, though not surprising in hindsight, is that the changing of the <code>windowHalfWidth</code> argument causes the largest difference between the languages. This makes sense because this argument determines how many values are meaned together in the beginning of the climatology calculations. And as the differences are due to rounding, that numerical fingerprint is boldest here.</p>
<p>Depending on how some of the arguments were tweaked, the tow languages very rarely would detect one event more or less than the other. This was due to the odd day being just above or below the threshold by ~0.001 degrees or so. Very rare, but so is existent, hypothetically.</p>
<p>Ultimately, I am very confident in saying that the outputs of these two languages are comparable.</p>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#overview">Overview</a></li>
      <li><a href="#pctile-comparisons"><code>pctile</code> comparisons</a></li>
      <li><a href="#smoothpercentilewidth-comparisons"><code>smoothPercentileWidth</code> comparisons</a></li>
      <li><a href="#windowhalfwidth-comparisons"><code>windowHalfWidth</code> comparisons</a></li>
      <li><a href="#minduration-comparisons"><code>minDuration</code> comparisons</a></li>
      <li><a href="#joinacrossgaps-comparisons"><code>joinAcrossGaps</code> comparisons</a></li>
      <li><a href="#conclusion">Conclusion</a></li>
      </ul>
</div>
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by Robert W. Schlegel, Eric C. J. Oliver, Albertus J. Smit.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="http://pkgdown.r-lib.org/">pkgdown</a>.</p>
</div>

      </footer>
</div>

  
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script><script>
  docsearch({
    
    
    apiKey: '2edc7627dae0471f3d765c3355bebbf3',
    indexName: 'heatwaver',
    inputSelector: 'input#search-input.form-control',
    transformData: function(hits) {
      return hits.map(function (hit) {
        hit.url = updateHitURL(hit);
        return hit;
      });
    }
  });
</script>
</body>
</html>
