# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fun1 <- function(x, windowHalfWidth) {
    .Call(`_heatwaveR_fun1`, x, windowHalfWidth)
}

fun1 <- function(x, windowHalfWidth) {
    .Call(`_heatwaveR_fun1`, x, windowHalfWidth)
}

mw_cpp <- function(d) {
    .Call(`_heatwaveR_mw_cpp`, d)
}

sumCpp <- function(x) {
    .Call(`_heatwaveR_sumCpp`, x)
}

rcpparma_hello_world <- function() {
    .Call(`_heatwaveR_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_heatwaveR_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_heatwaveR_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_heatwaveR_rcpparma_bothproducts`, x)
}

add_vecs <- function(a, b) {
    .Call(`_heatwaveR_add_vecs`, a, b)
}

