# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

clim_calc_cpp <- function(x, windowHalfWidth, pctile) {
    .Call('_heatwaveR_clim_calc_cpp', PACKAGE = 'heatwaveR', x, windowHalfWidth, pctile)
}

seqDates <- function(startYear, startMonth, startDay, endYear, endMonth, endDay) {
    .Call('_heatwaveR_seqDates', PACKAGE = 'heatwaveR', startYear, startMonth, startDay, endYear, endMonth, endDay)
}

