# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mw_cpp <- function(d) {
  .Call('_heatwaveR_mw_cpp', PACKAGE = 'heatwaveR', d)
}

mw_seq_cpp <- function(d) {
  .Call('_heatwaveR_mw_seq_cpp', PACKAGE = 'heatwaveR', d)
}

sumCpp <- function(x) {
  .Call('_heatwaveR_sumCpp', PACKAGE = 'heatwaveR', x)
}

rcpparma_hello_world <- function() {
  .Call('_heatwaveR_rcpparma_hello_world', PACKAGE = 'heatwaveR')
}

rcpparma_outerproduct <- function(x) {
  .Call('_heatwaveR_rcpparma_outerproduct', PACKAGE = 'heatwaveR', x)
}

rcpparma_innerproduct <- function(x) {
  .Call('_heatwaveR_rcpparma_innerproduct', PACKAGE = 'heatwaveR', x)
}

rcpparma_bothproducts <- function(x) {
  .Call('_heatwaveR_rcpparma_bothproducts', PACKAGE = 'heatwaveR', x)
}

add_vecs <- function(a, b) {
  .Call('_heatwaveR_add_vecs', PACKAGE = 'heatwaveR', a, b)
}

